# Generated by Django 3.0.6 on 2020-05-31 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=70)),
                ('visitors_per_year', models.IntegerField()),
                ('age', models.IntegerField()),
                ('operational', models.BooleanField(default=True)),
            ],
        ),
    ]
